name: Build and Push Frontend & Backend to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Frontend Docker image
      run: |
        FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/frontend
        docker build ./Forntend --file ./Forntend/Dockerfile -t $FRONTEND_IMAGE:latest

    - name: Build Backend Docker image
      run: |
        BACKEND_IMAGE=ghcr.io/${{ github.repository_owner }}/backend
        docker build ./Backend --file ./Backend/Dockerfile -t $BACKEND_IMAGE:latest

    - name: Push Frontend Docker image
      run: |
        FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/frontend
        docker push $FRONTEND_IMAGE:latest

    - name: Push Backend Docker image
      run: |
        BACKEND_IMAGE=ghcr.io/${{ github.repository_owner }}/backend
        docker push $BACKEND_IMAGE:latest
